export const START_SELECTING = "START_SELECTING";
export const CONFIRM_BOOKING = "CONFIRM_BOOKING";
export const CHAIR_CHANGES = "CHAIR_CHANGES";
export const CHANGE_CUSTOMER_NAME = "CHANGE_CUSTOMER_NAME";
export const CHANGE_NUMBER_OF_SEATS = "CHANGE_NUMBER_OF_SEATS";
